# -*- coding: utf-8 -*-
PACKAGE_NAME        = "Excel 고급"
PACKAGE_ID          = "command-group:excel_ms"
PACKAGE_DESCRIPTION = "Microsoft Excel 스프레드시트로 수행되는 작업을 자동화합니다. 장치에 Microsoft Excel이 설치된 경우 이 패키지를 사용하십시오. 주요 액션: 비밀번호로 보호된 워크시트에 액세스(현재 통합 문서에서 암호로 보호된 워크시트에 액세스합니다.)、통합 문서 추가(지정된 통합 문서의 모든 워크시트를 현재 열려 있는 통합 문서의 끝에 추...)、워크시트 추가(다른 통합 문서의 워크시트를 현재 통합 문서에 추가합니다.)、닫기(현재 통합 문서를 닫고 파일을 닫을 때 변경 사항을 저장할 수 있는 옵션...)、Excel을 PDF로 변환(전체 통합 문서, 통합 문서의 특정 워크시트 또는 CSV 파일을 PDF...) 외 54개."

ACTIONS = [
    {"action": "비밀번호로 보호된 워크시트에 액세스", "data_item_name": "excel_ms#unprotectworksheet", "description": "현재 통합 문서에서 암호로 보호된 워크시트에 액세스합니다."},
    {"action": "통합 문서 추가", "data_item_name": "excel_ms#appendworkbook", "description": "지정된 통합 문서의 모든 워크시트를 현재 열려 있는 통합 문서의 끝에 추가합니다."},
    {"action": "워크시트 추가", "data_item_name": "excel_ms#appendworksheet", "description": "다른 통합 문서의 워크시트를 현재 통합 문서에 추가합니다."},
    {"action": "닫기", "data_item_name": "excel_ms#closespreadsheet", "description": "현재 통합 문서를 닫고 파일을 닫을 때 변경 사항을 저장할 수 있는 옵션을 제공합니다."},
    {"action": "Excel을 PDF로 변환", "data_item_name": "excel_ms#converttopdf", "description": "전체 통합 문서, 통합 문서의 특정 워크시트 또는 CSV 파일을 PDF 파일로 변환합니다."},
    {"action": "통합 문서 생성", "data_item_name": "excel_ms#createspreadsheet", "description": "Microsoft Excel 통합 문서 또는 CSV 파일을 생성합니다."},
    {"action": "워크시트 생성", "data_item_name": "excel_ms#createworksheet", "description": "현재 통합 문서에서 워크시트를 생성합니다."},
    {"action": "셀 삭제", "data_item_name": "excel_ms#deletecells", "description": "현재 워크시트 또는 CSV 파일에서 활성 셀 또는 특정 셀을 삭제합니다."},
    {"action": "테이블 열 삭제", "data_item_name": "excel_ms#deletetablecolumn", "description": "테이블의 열을 삭제합니다."},
    {"action": "통합 문서 링크 끊기", "data_item_name": "excel_ms#deleteworkbooklinks", "description": "현재 통합 문서의 통합 문서 링크를 끊어 연결된 데이터를 정적 값으로 변환합니다."},
    {"action": "워크시트 삭제", "data_item_name": "excel_ms#deletespreadsheet", "description": "현재 통합 문서에서 스프레드시트를 삭제합니다."},
    {"action": "실시간 화면 업데이트 비활성화 또는 활성화", "data_item_name": "excel_ms#enabledisableautoupdate", "description": "실시간 화면 업데이트를 비활성화합니다."},
    {"action": "필터", "data_item_name": "excel_ms#filtertablev2", "description": "테이블 또는 워크시트에서 데이터를 필터링합니다."},
    {"action": "찾기", "data_item_name": "excel_ms#find", "description": "Microsoft Excel 스프레드시트 또는 CSV 파일에서 특정 문자열을 찾습니다."},
    {"action": "다음 빈 셀 찾기", "data_item_name": "excel_ms#findnextemptycell", "description": "다음 빈 셀을 찾습니다."},
    {"action": "셀 색상 가져오기", "data_item_name": "excel_ms#getcellcolor", "description": "셀의 배경 색상 또는 텍스트를 검색합니다."},
    {"action": "현재 워크시트 이름 가져오기", "data_item_name": "excel_ms#getcurrentworksheetname", "description": "현재 워크시트의 이름을 검색하여 문자열 변수에 할당합니다."},
    {"action": "여러 셀 가져오기", "data_item_name": "excel_ms#getmultiplecells", "description": "Microsoft Excel 스프레드시트의 셀에서 값을 검색해 테이블 변수에 저장합니다."},
    {"action": "행 개수 가져오기", "data_item_name": "excel_ms#getnumberofrows", "description": "데이터가 포함된 행 수를 검색합니다."},
    {"action": "민감도 라벨 가져오기", "data_item_name": "excel_ms#getsensitivitylabel", "description": "Microsoft Excel 스프레드시트에 적용된 민감도 라벨을 검색합니다"},
    {"action": "단일 셀 가져오기", "data_item_name": "excel_ms#getsinglecell", "description": "Microsoft Excel 스프레드시트 또는 CSV 파일의 단일 셀에서 값을 검색해 문자열 변수에 저장합니다."},
    {"action": "셀 주소 가져오기", "data_item_name": "excel_ms#getsinglecelladdress", "description": "활성 셀의 위치를 검색하여 문자열 변수에 저장합니다. 이 작업은 .xlsx 및 .xlxm 파일을 지원합니다."},
    {"action": "열 이름 가져오기", "data_item_name": "excel_ms#getsinglecolumnname", "description": "특정 셀이 포함된 열 이름을 검색하여 문자열 변수에 저장합니다. 이 작업은 .xlsx 및 .xlxm 파일을 지원합니다."},
    {"action": "행 번호 가져오기", "data_item_name": "excel_ms#getsinglerownumber", "description": "특정 셀이 포함된 행 번호를 검색하여 문자열 변수에 저장합니다. 이 작업은 .xlsx 및 .xlxm 파일을 지원합니다."},
    {"action": "테이블 범위 가져오기", "data_item_name": "excel_ms#tablegetrange", "description": "워크시트에서 테이블의 범위를 검색하여 문자열 변수에 출력을 저장합니다."},
    {"action": "통합 문서 링크 가져오기", "data_item_name": "excel_ms#getworkbooklinks", "description": "현재 통합 문서 내의 모든 통합 문서 링크 참조를 검색합니다."},
    {"action": "워크시트를 데이터 테이블로 가져오기", "data_item_name": "excel_ms#getworksheetasdatatable", "description": "워크시트에서 데이터를 검색하여 테이블 변수에 저장합니다."},
    {"action": "워크시트 이름 가져오기", "data_item_name": "excel_ms#getworksheetnames", "description": "모든 워크시트의 이름을 검색해 문자열 데이터 유형의 목록 변수에 할당합니다."},
    {"action": "셀로 이동", "data_item_name": "excel_ms#gotocell", "description": "커서를 Microsoft Excel 스트레드시트 또는 CSV 파일의 특정 셀로 이동합니다."},
    {"action": "다음 빈 셀로 이동", "data_item_name": "excel_ms#gotonextemptycell", "description": "현재 워크시트의 다음 빈 셀을 찾습니다. 빈 셀을 찾을 방향을 왼쪽, 오른쪽, 위 또는 아래로 지정할 수 있습니다."},
    {"action": "선택 영역에서 행/열 숨기기", "data_item_name": "excel_ms#hiderowscolumnsinselection", "description": "현재 워크시트의 행 또는 열을 숨깁니다."},
    {"action": "워크시트 숨기기", "data_item_name": "excel_ms#hideworksheet", "description": "현재 통합 문서에서 워크시트를 숨깁니다."},
    {"action": "행/열 삽입/삭제", "data_item_name": "excel_ms#insertdeleterowcolumn", "description": "현재 워크시트 또는 CSV 파일에서 행 또는 열을 생성하거나 제거합니다."},
    {"action": "테이블 열 삽입", "data_item_name": "excel_ms#inserttablecolumn", "description": "테이블에 열을 삽입합니다."},
    {"action": "열기", "data_item_name": "excel_ms#openspreadsheet", "description": "Microsoft Excel 스프레드시트 또는 CSV 파일을 엽니다. 비밀번호 등을 사용해 읽기 전용 또는 쓰기 전용 모드로 스프레드시트를 열 수 있습니다."},
    {"action": "통합 문서 보호", "data_item_name": "excel_ms#protectworkbook", "description": "비밀번호로 통합 문서와 해당 구조를 보호합니다. 이렇게 하면 비밀번호 없이 다른 사용자가 통합 문서를 열거나 변경(이동, 추가, 삭제, 숨기기 또는 워크시트의 이름 바꾸기)할 수 없습니다."},
    {"action": "비밀번호 보호 워크시트", "data_item_name": "excel_ms#protectworksheet", "description": "비밀번호로 워크시트를 보호합니다. 워크시트에서 제한할 작업을 지정할 수 있습니다."},
    {"action": "셀 수식 읽기", "data_item_name": "excel_ms#readcellformula", "description": "활성 셀 또는 특정 셀에서 사용할 수 있는 수식을 검색하여 출력을 문자열 변수에 할당합니다. 특정 셀이 수식을 포함하지 않는다면 공백 값이 반환됩니다."},
    {"action": "열 읽기", "data_item_name": "excel_ms#readexcelcolumn", "description": "열에서 데이터를 추출하여 문자열 데이터 유형의 목록 변수에 저장합니다."},
    {"action": "행 읽기", "data_item_name": "excel_ms#readexcelrow", "description": "행에서 데이터를 추출하여 문자열 데이터 유형의 목록 변수에 저장합니다."},
    {"action": "빈 행 제거", "data_item_name": "excel_ms#removeblankrows", "description": "현재 워크시트에서 빈 행을 제거합니다."},
    {"action": "워크시트 이름 바꾸기", "data_item_name": "excel_ms#renameworksheet", "description": "현재 통합 문서의 워크시트 이름을 바꿉니다."},
    {"action": "바꾸기", "data_item_name": "excel_ms#replace", "description": "특정 문자열이 포함된 셀을 찾아 다른 문자열로 바꿉니다. 이 작업은 .xlsx, .xlsm 및 .csv 파일을 지원합니다."},
    {"action": "시트 개수 검색", "data_item_name": "excel_ms#retrievesheetscount", "description": "현재 통합 문서에서 사용할 수 있는 시트 수를 검색하여 숫자 변수에 저장합니다."},
    {"action": "매크로 실행", "data_item_name": "excel_ms#runmacro", "description": "워크시트에서 매크로를 실행합니다."},
    {"action": "다른 이름으로 저장", "data_item_name": "excel_ms#saveas", "description": "지정된 위치에 통합 문서의 복사본을 저장합니다."},
    {"action": "통합 문서 저장", "data_item_name": "excel_ms#savespreadsheet", "description": "현재 통합 문서를 저장합니다."},
    {"action": "셀/행/열 선택", "data_item_name": "excel_ms#selectrowcolumncellrange", "description": "셀, 행 또는 열을 선택합니다."},
    {"action": "셀 설정", "data_item_name": "excel_ms#setcell", "description": "Microsoft Excel 스프레드시트 또는 CSV 파일의 활성 셀 또는 특정 셀에서 값을 설정합니다. 이 작업을 사용하여 수식을 설정할 수도 있습니다."},
    {"action": "셀 수식 설정", "data_item_name": "excel_ms#setcellformula", "description": "Microsoft Excel 스프레드시트 또는 CSV 파일의 활성 셀 또는 특정 셀에서 수식을 설정합니다."},
    {"action": "민감도 라벨 설정", "data_item_name": "excel_ms#setsensitivitylabel", "description": "Microsoft Excel 스프레드시트에서 민감도 라벨을 설정합니다"},
    {"action": "분류", "data_item_name": "excel_ms#sorttablev2", "description": "테이블 또는 워크시트의 열에서 데이터를 정렬합니다."},
    {"action": "시트로 전환", "data_item_name": "excel_ms#switchtosheet", "description": "Microsoft Excel 파일에서 특정 시트를 활성화합니다."},
    {"action": "모든 워크시트 숨기기 취소", "data_item_name": "excel_ms#unhideallworksheet", "description": "현재 워크시트에서 모든 워크시트를 숨기기 취소합니다."},
    {"action": "선택 영역에서 행/열 숨기기 취소", "data_item_name": "excel_ms#unhiderowscolumnsinselection", "description": "현재 워크시트에서 숨겨진 행 또는 열을 숨기기 취소합니다."},
    {"action": "워크시트 숨기기 취소", "data_item_name": "excel_ms#unhideworksheet", "description": "현재 통합 문서에서 특정 워크시트를 숨기기 취소합니다."},
    {"action": "통합 문서 보호 해제", "data_item_name": "excel_ms#unprotectworkbook", "description": "통합 문서 및 해당 구조의 보호를 해제하여 통합 문서에 적용된 모든 제한을 제거합니다."},
    {"action": "통합 문서 링크 변경", "data_item_name": "excel_ms#updateworkbooklinks", "description": "현재 통합 문서의 통합 문서 링크를 지정된 새 원본으로 변경합니다."},
    {"action": "데이터 테이블로부터 쓰기", "data_item_name": "excel_ms#writedatatabletoworksheet", "description": "데이터 테이블의 값을 워크시트에 씁니다."},
]