# -*- coding: utf-8 -*-
PACKAGE_NAME        = "Genesys"
PACKAGE_ID          = "command-group:genesys"
PACKAGE_DESCRIPTION = "Genesys Rest API에 대한 작업을 제공합니다. 주요 액션: OAuth 인증(클라이언트 자격 증명 부여를 사용하여 OAuth 인증)、대화 세부 정보 가져오기(대화에 대한 세부 정보 가져오기)、부서에 역할 추가(부서에서 역할 부여 하기)、부서에 역할 일괄 추가(부서에서 사용자 역할 일괄 추가)、부서에서 역할 일괄 제거(부서에서 사용자 역할 일괄 추가) 외 49개."

ACTIONS = [
    {"action": "OAuth 인증", "data_item_name": "genesys#authentication", "description": "클라이언트 자격 증명 부여를 사용하여 OAuth 인증"},
    {"action": "대화 세부 정보 가져오기", "data_item_name": "genesys#conversation_getbyid", "description": "대화에 대한 세부 정보 가져오기"},
    {"action": "부서에 역할 추가", "data_item_name": "genesys#division_adduserroleindivision", "description": "부서에서 역할 부여 하기"},
    {"action": "부서에 역할 일괄 추가", "data_item_name": "genesys#division_bulkadduserroleindivision", "description": "부서에서 사용자 역할 일괄 추가"},
    {"action": "부서에서 역할 일괄 제거", "data_item_name": "genesys#division_bulkremoveuserroleindivision", "description": "부서에서 사용자 역할 일괄 추가"},
    {"action": "부서에서 역할 일괄 바꾸기", "data_item_name": "genesys#division_bulkreplaceuserroleindivision", "description": "부서에서 사용자 역할 일괄 바꾸기"},
    {"action": "홈 부서 가져오기", "data_item_name": "genesys#division_getdivisionhome", "description": "조직의 홈 부서를 검색합니다. 개체 수는 포함되지 않습니다."},
    {"action": "부서 목록/검색", "data_item_name": "genesys#division_listdivisions", "description": "조직에 대해 정의된 모든 부서 목록 검색"},
    {"action": "부서에서 역할 제거", "data_item_name": "genesys#division_removeuserroleindivision", "description": "부서에서 역할 부여 삭제"},
    {"action": "연락처 만들기", "data_item_name": "genesys#externalcontact_create", "description": "외부 연락처 만들기"},
    {"action": "연락처 삭제", "data_item_name": "genesys#externalcontact_deletecontact", "description": "외부 연락처 삭제"},
    {"action": "연락처 목록/검색", "data_item_name": "genesys#externalcontact_listcontacts", "description": "연락처 ID 또는 검색 쿼리로 외부 연락처 목록을 가져옵니다. ID 또는 검색 쿼리가 필요합니다."},
    {"action": "연락처 업데이트", "data_item_name": "genesys#externalcontact_update", "description": "외부 연락처 업데이트"},
    {"action": "그룹에 구성원 일괄 추가", "data_item_name": "genesys#group_addmembers", "description": "그룹에 구성원 일괄 추가"},
    {"action": "구성원 삭제", "data_item_name": "genesys#group_deletememebers", "description": "그룹 구성원 삭제"},
    {"action": "그룹 목록", "data_item_name": "genesys#group_list", "description": "모든 그룹 목록"},
    {"action": "구성원 목록", "data_item_name": "genesys#group_listmembers", "description": "그룹의 모든 구성원 목록"},
    {"action": "라우팅 언어 추가", "data_item_name": "genesys#language_add", "description": "사용자에게 라우팅 언어 추가"},
    {"action": "사용자에게 라우팅 언어 일괄 추가", "data_item_name": "genesys#language_bulkaddroutinglanguage", "description": "사용자에게 라우팅 언어 일괄 추가"},
    {"action": "사용자의 라우팅 언어 목록", "data_item_name": "genesys#language_list", "description": "사용자의 라우팅 언어 목록"},
    {"action": "모든 라우팅 언어 목록", "data_item_name": "genesys#language_listsupportedroutinglanguages", "description": "지원되는 언어 목록 가져오기"},
    {"action": "사용자의 라우팅 언어 제거", "data_item_name": "genesys#language_removeuserroutinglanguage", "description": "사용자의 라우팅 언어 제거"},
    {"action": "조직 만들기", "data_item_name": "genesys#organization_create", "description": "외부 조직 만들기"},
    {"action": "조직 삭제", "data_item_name": "genesys#organization_delete", "description": "외부 조직 삭제"},
    {"action": "조직 가져오기", "data_item_name": "genesys#organization_get", "description": "외부 조직에 대한 세부 정보 가져오기"},
    {"action": "조직 목록/검색", "data_item_name": "genesys#organization_search", "description": "쿼리가 있는 외부 조직 목록/검색"},
    {"action": "조직 업데이트", "data_item_name": "genesys#organization_update", "description": "새 정보로 외부 조직을 업데이트합니다. 업데이트가 필요 없는 경우 필드를 비워 두십시오."},
    {"action": "전화 할당", "data_item_name": "genesys#edgephone_assignphone", "description": "사용자에게 전화 라인 할당"},
    {"action": "전화 만들기", "data_item_name": "genesys#edgephone_createphone", "description": "전화 만들기"},
    {"action": "전화 기본 설정 목록", "data_item_name": "genesys#edgephonebasesetting_listphonebasesettings", "description": "전화 기본 설정 목록"},
    {"action": "전화 목록/검색", "data_item_name": "genesys#edgephone_listphones", "description": "전화 목록/검색"},
    {"action": "사이트 목록/검색", "data_item_name": "genesys#edgesite_listsites", "description": "사이트 목록/검색"},
    {"action": "전화 제거", "data_item_name": "genesys#edgephone_removephone", "description": "Genesys: 전화 제거전화 제거필요한 Bot Agent 버전: 21.210 이상"},
    {"action": "대기열에 추가", "data_item_name": "genesys#queue_add", "description": "대기열에 사용자 추가"},
    {"action": "구성원 목록", "data_item_name": "genesys#queue_list", "description": "대기열의 모든 구성원 나열"},
    {"action": "대기열 목록/검색", "data_item_name": "genesys#queue_listqueues", "description": "조직에 대해 정의된 모든 대기열 목록 검색"},
    {"action": "대기열에서 제거", "data_item_name": "genesys#queue_remove", "description": "대기열에서 사용자 제거"},
    {"action": "역할에 사용자 추가", "data_item_name": "genesys#role_adduserstorole", "description": "역할에 사용자 목록 추가"},
    {"action": "역할 목록/검색", "data_item_name": "genesys#role_listroles", "description": "조직에 대해 정의된 모든 역할의 목록 검색"},
    {"action": "사용자의 역할 목록", "data_item_name": "genesys#role_listuserroles", "description": "사용자의 역할과 권한 목록을 반환합니다."},
    {"action": "역할의 사용자 목록", "data_item_name": "genesys#role_listusersinrole", "description": "지정된 역할의 사용자 목록을 가져옵니다. 지정된 역할에 있는 사용자의 uuid 배열을 가져옵니다."},
    {"action": "역할에서 사용자 제거", "data_item_name": "genesys#role_removeuserstorole", "description": "역할에서 사용자 목록 제거"},
    {"action": "사용자의 역할 설정", "data_item_name": "genesys#role_setuserroles", "description": "사용자의 역할 설정"},
    {"action": "사용자 라우팅 기술 추가", "data_item_name": "genesys#skill_adduserroutingskill", "description": "사용자 라우팅 기술 추가"},
    {"action": "라우팅 기술 일괄 추가", "data_item_name": "genesys#skill_bulkaddroutingskill", "description": "사용자에게 라우팅 기술 일괄 추가"},
    {"action": "라우팅 기술 일괄 바꾸기", "data_item_name": "genesys#skill_bulkreplaceroutingskill", "description": "사용자에게 라우팅 기술을 대량으로 대체"},
    {"action": "라우팅 기술 목록/검색", "data_item_name": "genesys#skill_listroutingskills", "description": "라우팅 기술 목록 가져오기"},
    {"action": "사용자의 라우팅 기술 목록", "data_item_name": "genesys#skill_listuserroutingskills", "description": "사용자의 라우팅 기술 목록 가져오기"},
    {"action": "사용자 라우팅 기술 제거", "data_item_name": "genesys#skill_removeuserroutingskill", "description": "사용자 라우팅 기술 제거"},
    {"action": "사용자 생성", "data_item_name": "genesys#user_create", "description": "새 사용자 만들기"},
    {"action": "사용자 삭제", "data_item_name": "genesys#user_delete", "description": "기존 사용자 삭제"},
    {"action": "사용자 가져오기", "data_item_name": "genesys#user_getdetail", "description": "기존 사용자에 대한 세부 정보 가져오기"},
    {"action": "사용자 목록/검색", "data_item_name": "genesys#list_users", "description": "사용자 목록/검색"},
    {"action": "사용자 업데이트", "data_item_name": "genesys#user_update", "description": "기존 사용자를 업데이트합니다. 업데이트가 필요 없는 경우 필드를 비워 두십시오."},
]