# -*- coding: utf-8 -*-
PACKAGE_NAME        = "Microsoft 365 Excel"
PACKAGE_ID          = "command-group:office 365 excel"
PACKAGE_DESCRIPTION = "Microsoft Excel의 온라인 버전에서 태스크를 자동화합니다. 주요 액션: 열 자동 맞춤(지정된 세션에서 워크시트의 열 너비를 조정(자동 맞춤)합니다.)、행 자동 맞춤(지정된 세션에서 워크시트의 행 높이를 조정(자동 맞춤)합니다.)、닫기(통합 문서를 닫습니다)、연결(OAuth2 인증으로 온라인 버전의 Microsoft 365 Excel에...)、워크시트 복사(한 워크시트에서 다른 워크시트로 워크시트 값을 복사합니다. 이 작업은 기...) 외 47개."

ACTIONS = [
    {"action": "열 자동 맞춤", "data_item_name": "office 365 excel#autofitcolumns", "description": "지정된 세션에서 워크시트의 열 너비를 조정(자동 맞춤)합니다."},
    {"action": "행 자동 맞춤", "data_item_name": "office 365 excel#autofitrows", "description": "지정된 세션에서 워크시트의 행 높이를 조정(자동 맞춤)합니다."},
    {"action": "닫기", "data_item_name": "office 365 excel#close", "description": "통합 문서를 닫습니다"},
    {"action": "연결", "data_item_name": "office 365 excel#connect", "description": "OAuth2 인증으로 온라인 버전의 Microsoft 365 Excel에 연결하여 Excel 작업을 수행합니다."},
    {"action": "워크시트 복사", "data_item_name": "office 365 excel#copysheet", "description": "한 워크시트에서 다른 워크시트로 워크시트 값을 복사합니다. 이 작업은 기존 값을 덮어씁니다."},
    {"action": "테이블 생성", "data_item_name": "office 365 excel#createtable", "description": "지정된 테이블 범위에 새 테이블을 생성합니다."},
    {"action": "통합 문서 생성", "data_item_name": "office 365 excel#createworkbook", "description": "새 통합 문서를 생성합니다"},
    {"action": "시트 생성", "data_item_name": "office 365 excel#createworksheet", "description": "현재 통합 문서에 빈 시트를 추가합니다."},
    {"action": "셀 삭제", "data_item_name": "office 365 excel#deletecell", "description": "현재 워크시트에서 활성 셀 또는 특정 셀을 삭제합니다."},
    {"action": "범위 삭제", "data_item_name": "office 365 excel#deleterange", "description": "특정 범위의 셀을 삭제합니다."},
    {"action": "행 또는 열 삭제", "data_item_name": "office 365 excel#deleterowcolumn", "description": "현재 워크시트에서 행이나 열을 제거합니다."},
    {"action": "테이블 삭제", "data_item_name": "office 365 excel#deletetable", "description": "활성 워크시트에서 테이블을 삭제합니다."},
    {"action": "워크시트 삭제", "data_item_name": "office 365 excel#deleteworksheet", "description": "현재 통합 문서에서 스프레드시트를 삭제합니다."},
    {"action": "연결 끊기", "data_item_name": "office 365 excel#disconnect", "description": "Office 365 애플리케이션에서 연결을 종료합니다."},
    {"action": "찾기", "data_item_name": "office 365 excel#find", "description": "Microsoft 365 Excel 스프레드시트에서 특정 문자열을 찾습니다."},
    {"action": "다음 빈 셀 찾기", "data_item_name": "office 365 excel#findnextemptycell", "description": "다음 빈 셀을 찾습니다."},
    {"action": "셀에 서식 적용", "data_item_name": "office 365 excel#formatcell", "description": "셀 또는 셀 그룹의 형식을 설정합니다."},
    {"action": "셀 가져오기", "data_item_name": "office 365 excel#getcell", "description": "셀의 값을 검색합니다."},
    {"action": "셀 또는 텍스트 색상 가져오기", "data_item_name": "office 365 excel#getcellcolor", "description": "RGB 값으로 셀의 배경색 또는 텍스트 색상을 검색합니다."},
    {"action": "현재 워크시트 이름 가져오기", "data_item_name": "office 365 excel#getcurrentworksheetname", "description": "현재 활성 워크시트의 이름을 검색할 수 있습니다."},
    {"action": "여러 셀 가져오기", "data_item_name": "office 365 excel#getmultiplecells", "description": "워크시트 내의 여러 셀 값을 검색하고 출력을 변수에 할당합니다."},
    {"action": "행 수 가져오기", "data_item_name": "office 365 excel#getrowcount", "description": "워크시트에서 데이터가 포함된 행 수를 검색합니다."},
    {"action": "셀 주소 가져오기", "data_item_name": "office 365 excel#getsinglecelladdress", "description": "활성 셀의 위치를 검색하여 문자열 변수에 저장합니다."},
    {"action": "열 이름 가져오기", "data_item_name": "office 365 excel#getsinglecolumnname", "description": "특정 셀을 포함하는 열 이름을 검색하여 문자열 변수에 저장합니다."},
    {"action": "행 번호 가져오기", "data_item_name": "office 365 excel#getsinglerownumber", "description": "특정 셀을 포함하는 행 번호를 검색하여 문자열 변수에 저장합니다."},
    {"action": "테이블 열 가져오기", "data_item_name": "office 365 excel#gettablecolumn", "description": "지정된 테이블 및 열 인덱스의 열 값을 검색하고 값을 목록 변수에 할당합니다."},
    {"action": "테이블 이름 가져오기", "data_item_name": "office 365 excel#gettablenames", "description": "통합 문서에 있는 모든 테이블의 이름을 검색하여 목록 변수에 할당합니다."},
    {"action": "테이블 행 가져오기", "data_item_name": "office 365 excel#gettablerow", "description": "지정된 테이블 및 행 인덱스의 행 값을 검색하고 값을 변수에 할당합니다."},
    {"action": "테이블 행 개수 가져오기", "data_item_name": "office 365 excel#gettablerowcount", "description": "지정된 테이블의 행 수를 검색하고 값을 숫자 변수에 할당합니다."},
    {"action": "워크시트를 데이터 테이블로 가져오기", "data_item_name": "office 365 excel#getworksheetasdatatable", "description": "워크시트에서 데이터를 검색하여 테이블 변수에 저장합니다."},
    {"action": "워크시트 이름 가져오기", "data_item_name": "office 365 excel#getworksheetnames", "description": "통합 문서에 있는 모든 워크시트의 이름을 검색합니다."},
    {"action": "셀로 이동", "data_item_name": "office 365 excel#gotocell", "description": "워크시트의 특정 셀로 커서를 이동합니다."},
    {"action": "다음 빈 셀로 이동", "data_item_name": "office 365 excel#gotonextemptycell", "description": "현재 워크시트의 다음 빈 셀을 찾습니다. 빈 셀을 찾을 방향을 왼쪽, 오른쪽, 위 또는 아래로 지정할 수 있습니다."},
    {"action": "워크시트 숨기기", "data_item_name": "office 365 excel#hideworksheet", "description": "현재 통합 문서에서 워크시트를 숨깁니다."},
    {"action": "셀 삽입", "data_item_name": "office 365 excel#insertcell", "description": "기존 값을 덮어쓰지 않고 현재 워크시트의 활성 셀 또는 특정 셀에 값을 삽입합니다."},
    {"action": "범위 삽입", "data_item_name": "office 365 excel#insertrange", "description": "기존 값을 덮어쓰지 않고 현재 워크시트에 범위를 삽입합니다."},
    {"action": "행 또는 열 삽입", "data_item_name": "office 365 excel#insertrowcolumn", "description": "현재 워크시트에 행 또는 열을 생성합니다."},
    {"action": "열기", "data_item_name": "office 365 excel#openworkbook", "description": "통합 문서를 엽니다. 자동화 시퀀스의 시작 부분에 이 작업을 삽입합니다."},
    {"action": "셀 붙여넣기", "data_item_name": "office 365 excel#pastecell", "description": "셀에서 값을 복사하여 지정된 셀에 붙여넣습니다. 대상 셀의 기존 값을 덮어씁니다."},
    {"action": "셀 서식 읽기", "data_item_name": "office 365 excel#readcellformat", "description": "활성 또는 지정된 셀의 형식(예: 세로 또는 가로 정렬 및 줄 바꿈 텍스트)을 검색하고 출력을 문자열 변수에 할당합니다."},
    {"action": "셀 수식 읽기", "data_item_name": "office 365 excel#readcellformula", "description": "활성 또는 특정 셀에서 수식을 검색하고 출력을 문자열 변수에 할당합니다. 지정된 셀에 수식이 포함되어 있지 않으면 빈 값을 반환합니다."},
    {"action": "열 읽기", "data_item_name": "office 365 excel#readcolumn", "description": "열에서 데이터를 추출하여 목록 변수에 저장합니다."},
    {"action": "행 읽기", "data_item_name": "office 365 excel#readrow", "description": "행에서 데이터를 추출하여 변수에 저장합니다."},
    {"action": "테이블 이름 바꾸기", "data_item_name": "office 365 excel#renametable", "description": "테이블 이름을 바꿉니다."},
    {"action": "워크시트 이름 바꾸기", "data_item_name": "office 365 excel#renameworksheet", "description": "현재 통합 문서에서 워크시트의 이름을 바꿉니다."},
    {"action": "시트 개수 검색", "data_item_name": "office 365 excel#retrievesheetscount", "description": "현재 통합 문서에서 사용 가능한 시트 수를 검색하여 숫자 변수에 저장합니다."},
    {"action": "셀 설정", "data_item_name": "office 365 excel#setcell", "description": "Excel 스프레드시트 또는 CSV 파일의 활성 또는 특정 셀에 값을 설정합니다."},
    {"action": "셀 색상 설정하기", "data_item_name": "office 365 excel#setcellcolor", "description": "워크시트에서 활성 셀 또는 특정 셀의 배경이나 텍스트에 색을 설정합니다."},
    {"action": "셀 수식 설정", "data_item_name": "office 365 excel#setcellformula", "description": "워크시트에서 지정된 셀의 수식을 설정합니다."},
    {"action": "워크시트 보기", "data_item_name": "office 365 excel#showworksheet", "description": "숨겨진 워크시트를 표시합니다."},
    {"action": "시트로 전환", "data_item_name": "office 365 excel#switchtosheet", "description": "Microsoft Excel 파일에서 특정 시트를 활성화합니다."},
    {"action": "데이터 테이블로부터 쓰기", "data_item_name": "office 365 excel#writedatatabletoworksheet", "description": "데이터 테이블의 값을 워크시트에 씁니다."},
]